-- ===========================================
-- ESQUEMAS
-- ===========================================

-- Separar la lógica de usuarios de la lógica de negocio
CREATE SCHEMA IF NOT EXISTS gestion_usuario;
CREATE SCHEMA IF NOT EXISTS logica_negocio;

-- ===========================================
-- TABLA USUARIO
-- ===========================================

CREATE TABLE IF NOT EXISTS gestion_usuario.usuario (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID único del usuario
    nombre_usuario VARCHAR(50) NOT NULL UNIQUE,                      -- Nombre de usuario
    telefono_usuario VARCHAR(15),                                    -- Teléfono del usuario (opcional)
    foto_usuario BYTEA,                                              -- Foto de perfil (opcional)
    email_usuario VARCHAR(150) NOT NULL UNIQUE,                      -- Email único
    passwd_usuario VARCHAR(255) NOT NULL,                            -- Contraseña (hashed)
    rol_usuario VARCHAR(50)                                           -- Rol: cliente, admin, etc.
);

-- ===========================================
-- TABLA PRODUCTO
-- ===========================================

CREATE TABLE IF NOT EXISTS logica_negocio.producto (
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID único del producto
    nombre_producto VARCHAR(255) NOT NULL,                           -- Nombre del producto
    descripcion_producto TEXT,                                       -- Descripción detallada
    precio_producto NUMERIC(10, 2) NOT NULL,                         -- Precio unitario
    stock_producto INTEGER NOT NULL,                                  -- Stock disponible
    categoria_producto VARCHAR(50),                                   -- Categoría (ej: pasteles, cupcakes)
    imagen_producto BYTEA                                             -- Imagen del producto
);

-- ===========================================
-- TABLA PEDIDO
-- ===========================================

CREATE TABLE IF NOT EXISTS logica_negocio.pedido (
    id_pedido BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- ID único del pedido
    id_usuario BIGINT NOT NULL,                                       -- Usuario que hizo el pedido
    fecha_pedido TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Fecha de creación
    direccion_pedido VARCHAR(255) NOT NULL,                           -- Dirección de entrega
    estado_pedido VARCHAR(50) NOT NULL DEFAULT 'Pendiente',           -- Estado actual del pedido
    total_pedido NUMERIC(10, 2) NOT NULL,                             -- Total del pedido
    CONSTRAINT fk_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES gestion_usuario.usuario(id_usuario)
        ON DELETE CASCADE                                             -- Si se elimina usuario, también sus pedidos
);

-- ===========================================
-- TABLA DETALLE_PEDIDO (actualizada)
-- ===========================================

CREATE TABLE IF NOT EXISTS logica_negocio.detalle_pedido (
    id_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- ID único del detalle
    id_pedido BIGINT NOT NULL,                                        -- Pedido al que pertenece
    id_producto BIGINT,                                               -- Producto del detalle (puede quedar NULL si se borra)
    nombre_producto VARCHAR(255) NOT NULL,                            -- Nombre del producto al momento del pedido
    cantidad_producto INTEGER NOT NULL,                                -- Cantidad pedida
    precio_unitario NUMERIC(10, 2) NOT NULL,                           -- Precio unitario en el momento del pedido
    subtotal NUMERIC(10, 2) NOT NULL,                                  -- Subtotal = cantidad * precio_unitario
    CONSTRAINT fk_pedido
        FOREIGN KEY (id_pedido)
        REFERENCES logica_negocio.pedido(id_pedido)
        ON DELETE CASCADE,                                             -- Si se elimina pedido, se borran detalles
    CONSTRAINT fk_producto
        FOREIGN KEY (id_producto)
        REFERENCES logica_negocio.producto(id_producto)
        ON DELETE SET NULL                                             -- Si se borra producto, id_producto queda NULL pero detalle se mantiene
);



-- ===========================================
-- TABLA CARRITO
-- ===========================================

CREATE TABLE IF NOT EXISTS logica_negocio.carrito (
    id_carrito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- ID único del carrito
    id_usuario BIGINT NOT NULL,                                       -- Usuario propietario del carrito
    fecha_carrito TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Fecha de creación/actualización
    direccion_carrito VARCHAR(255),                                     -- Dirección de entrega (opcional hasta confirmar)
    estado_carrito VARCHAR(50) NOT NULL DEFAULT 'ACTIVO',              -- Estado del carrito (ACTIVO, FINALIZADO)
    total_carrito NUMERIC(10, 2) NOT NULL DEFAULT 0,                   -- Total del carrito
    CONSTRAINT fk_usuario_carrito
        FOREIGN KEY (id_usuario)
        REFERENCES gestion_usuario.usuario(id_usuario)
        ON DELETE CASCADE                                             -- Si se elimina usuario, también su carrito
);

-- ===========================================
-- TABLA DETALLES_CARRITO
-- ===========================================

CREATE TABLE IF NOT EXISTS logica_negocio.detalles_carrito (
    id_detalle_carrito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID único del detalle
    id_carrito BIGINT NOT NULL,                                        -- Carrito al que pertenece
    id_producto BIGINT,                                                -- Producto del detalle (puede quedar NULL si se borra)
    nombre_producto VARCHAR(255) NOT NULL,                            -- Nombre del producto al momento de añadirlo
    cantidad_producto INTEGER NOT NULL,                                 -- Cantidad en el carrito
    precio_unitario NUMERIC(10, 2) NOT NULL,                           -- Precio unitario en el momento de añadirlo
    subtotal NUMERIC(10, 2) NOT NULL,                                  -- Subtotal = cantidad * precio_unitario
    CONSTRAINT fk_carrito_detalle
        FOREIGN KEY (id_carrito)
        REFERENCES logica_negocio.carrito(id_carrito)
        ON DELETE CASCADE,                                             -- Si se elimina carrito, se borran detalles
    CONSTRAINT fk_producto_carrito
        FOREIGN KEY (id_producto)
        REFERENCES logica_negocio.producto(id_producto)
        ON DELETE SET NULL                                             -- Si se borra producto, id_producto queda NULL pero detalle se mantiene
);

